#!/bin/bash
### Set Language
TEXTDOMAIN=virtualhost
action=$1

echo '# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
# BEGIN Hide My WP

# END Hide My WP
Header always unset X-Frame-Options
Header always unset X-Frame-Options' > /var/www/$1/.htaccess